[package]
name = "supervisor"
version = "0.0.1"
edition = "2021"

[dependencies]
fable_library_rust = { path = "./src/fable_modules/fable-library-rust" }
clap = { version = "~4.0", features = ["derive"] }
serde_json = "1.0"
zmq = "~0.10"

[lib]
path = "./src/main.rs"
