[package]
name = "tictactoe"
version = "0.0.1"
edition = "2021"

[dependencies]
supervisor = { path = "./lib_spi/supervisor" }
cli = { path = "./lib_spi/cli" }
client = { path = "./lib_spi/client" }

[lib]
path = "./main.rs"
