[package]
name = "tictactoe"
version = "0.0.1"
edition = "2021"

[dependencies]
client = { path = "./lib_spi/client" }
supervisor = { path = "./lib_spi/supervisor" }

[lib]
path = "./lib_spi/client/src/main.rs"
