
[package]
name = "client"
version = "0.0.1"
edition = "2021"

[dependencies]
iced = { version = "~0.6", features = ["async-std", "debug"] }
serde = { version = "~1.0", features = ["derive"] }
once_cell = "~1.15"

colored = "~2.0"
fable_library_rust = { path = "../supervisor/src/fable_modules/fable-library-rust" }
rand = "~0.8"
serde_json = "~1.0"
zmq = "~0.10"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = "~1.0"
directories-next = "~2.0"

[lib]
path = "./src/main.rs"
