name: fleek
on:
  push:
    branches: [gh-pages]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - run: perl -i -pe 's/"\/tictactoe\//"\//g' ./*

      - uses: actions/upload-artifact@v2
        with:
          name: fleek
          retention-days: 30

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v2
        with:
          name: fleek
          path: fleek

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: fleek
          publish_branch: fleek
