name: fleek
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: perl -i -pe 's/"\/tictactoe\//"\//g' ./*

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          retention-days: 30

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: fleek
